{
 "title": "owlk8s",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "query": "show tag values  with key = \"namespace\""
   },
   {
    "name": "DEPLOY",
    "query": "show tag values  with key = \"owner\" where namespace =~ /^$NAMESPACE$/"
   },
   {
    "name": "PODS",
    "query": "show tag values  with key = \"podname\" where owner =~ /^$DEPLOY$/"
   },
   {
    "name": "SERVICE",
    "query": "show tag values  with key = \"service\" where owner =~ /^$DEPLOY$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "q/s" }
   ],
   "targets": [
    {
     "alias": "$tag_podname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(first(\"requests\"), 1s) FROM \"INT_svcmetrics\" WHERE \"namespace\" =~ /^$NAMESPACE$/ and  \"owner\" =~ /^$DEPLOY$/ and \"podname\" =~ /^$PODS$/ and \"service\" =~ /^$SERVICE$/ and $timeFilter  GROUP BY time($__interval), \"podname\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "err/s" }
   ],
   "targets": [
    {
     "alias": "$tag_podname 4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(first(\"err4\"), 1s) FROM \"INT_svcmetrics\" WHERE \"namespace\" =~ /^$NAMESPACE$/ and  \"owner\" =~ /^$DEPLOY$/ and \"podname\" =~ /^$PODS$/ and \"service\" =~ /^$SERVICE$/ and $timeFilter  GROUP BY time($__interval), \"podname\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_podname 5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(first(\"err5\"), 1s) FROM \"INT_svcmetrics\" WHERE \"namespace\" =~ /^$NAMESPACE$/ and  \"owner\" =~ /^$DEPLOY$/ and \"podname\" =~ /^$PODS$/ and \"service\" =~ /^$SERVICE$/ and $timeFilter  GROUP BY time($__interval), \"podname\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_podname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT first(\"duration\")/1000 FROM \"INT_svcmetrics\" WHERE \"namespace\" =~ /^$NAMESPACE$/ and  \"owner\" =~ /^$DEPLOY$/ and \"podname\" =~ /^$PODS$/ and \"service\" =~ /^$SERVICE$/ and $timeFilter GROUP BY time($__interval), \"podname\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}