apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: owlk8s
  name: owlk8s
spec:
  selector:
    matchLabels:
      app: owlk8s
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: owlk8s
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: owlk8s:0.0.1
        imagePullPolicy: Never
        name: owlk8s
        env:
         - name: nodename
           valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
         - name: debug
           value: "true"
         - name: IFLXPORT
           value: "8086"
         - name: IFLXDB
           value: "influx"
         - name: IFLXTABLE
           value: "INT_svcmetrics"
         - name: IFLXHOST
           value: influxdb.influxdb
        envFrom:
        - secretRef:
           name: influxdb-creds-owlk8s
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
data:
  IFLXUSER: aW5mbHV4
  IFLXPASS: aW5mbHV4
kind: Secret
metadata:
  name: influxdb-creds-owlk8s
type: Opaque
